#!/usr/bin/env python3
"""Generate a public place-and-route design for nextpnr: N PicoRV32 cores, each with a 4 KB memory, sharing a single
clock and a single reset. Routable on an ECP5-45F up to roughly N=8.

usage: gen_stress.py N [K] > stress_top.v   (needs picorv32.v from https://github.com/YosysHQ/picorv32)

With K > 0 a shift register of K flip-flops is added whose clock enable is a single LUT output, i.e. one ordinary net
with K sinks next to otherwise routable logic. (With K=5000 and N=6 this did not make router1 slow, so it is not a
reproduction of the problem the router1 pull request is about.)
"""
import sys

n = int(sys.argv[1]) if len(sys.argv) > 1 else 12
k = int(sys.argv[2]) if len(sys.argv) > 2 else 0

print("// generated by gen_stress.py, N=%d" % n)
print("module stress_top (input clk, input rstn, output led);")
print("    reg [1:0] rst_sync = 2'b00;")
print("    always @(posedge clk) rst_sync <= {rst_sync[0], rstn};")
print("    wire resetn = rst_sync[1];")
print("    wire [%d:0] trap;" % (n - 1))
print("    wire [%d:0] observe;" % (n - 1))
for i in range(n):
    print(f"""
    wire        valid{i}, instr{i}, ready{i};
    wire [31:0] addr{i}, wdata{i}, rdata{i};
    wire [3:0]  wstrb{i};
    reg  [31:0] mem{i} [0:1023];
    reg  [31:0] rd{i};
    reg         rdy{i};
    always @(posedge clk) begin
        rdy{i} <= 1'b0;
        if (valid{i} && !rdy{i}) begin
            rdy{i} <= 1'b1;
            if (wstrb{i}[0]) mem{i}[addr{i}[11:2]][7:0]   <= wdata{i}[7:0];
            if (wstrb{i}[1]) mem{i}[addr{i}[11:2]][15:8]  <= wdata{i}[15:8];
            if (wstrb{i}[2]) mem{i}[addr{i}[11:2]][23:16] <= wdata{i}[23:16];
            if (wstrb{i}[3]) mem{i}[addr{i}[11:2]][31:24] <= wdata{i}[31:24];
            rd{i} <= mem{i}[addr{i}[11:2]];
        end
    end
    assign ready{i} = rdy{i};
    assign rdata{i} = rd{i};
    picorv32 #(.ENABLE_COUNTERS(1), .ENABLE_MUL(1), .ENABLE_DIV(1), .BARREL_SHIFTER(1), .COMPRESSED_ISA(1),
               .ENABLE_IRQ(1), .PROGADDR_RESET(32'h0)) cpu{i} (
        .clk(clk), .resetn(resetn), .trap(trap[{i}]),
        .mem_valid(valid{i}), .mem_instr(instr{i}), .mem_ready(ready{i}), .mem_addr(addr{i}), .mem_wdata(wdata{i}),
        .mem_wstrb(wstrb{i}), .mem_rdata(rdata{i}), .irq(32'b0));
    assign observe[{i}] = ^{{addr{i}, wdata{i}}};""")
print("    reg led_r;")
if k > 0:
    print("    reg [15:0] cnt = 16'd0;")
    print("    always @(posedge clk) cnt <= cnt + 16'd1;")
    print("    wire big_ce = (cnt[4:0] == 5'd7) ^ rstn;")
    print("    reg [%d:0] big = 0;" % (k - 1))
    print("    always @(posedge clk) if (big_ce) big <= {big[%d:0], big[%d] ^ led_r};" % (k - 2, k - 1))
    print("    wire big_x = ^big;")
    print("    always @(posedge clk) led_r <= ^{trap, observe} ^ big_x;")
else:
    print("    always @(posedge clk) led_r <= ^{trap, observe};")
print("    assign led = led_r;")
print("endmodule")
