#!/usr/bin/env python3
"""Generate an adversarial nextpnr design: N registers share a single clock enable computed by a LUT, and each register
is fed by an XOR of three pseudo-randomly chosen other registers.

The random connectivity is the worst case for routing: with N=8000 neither the current router1 nor the router1
options in the pull request had routed it after 5 minutes (about 45k arcs left), so it says little about real designs.
It is kept because it is the one design where the arcPenaltyCap option makes router1 slower per iteration.

usage: gen_fanout.py N [seed] > fanout_top.v
"""
import random
import sys

n = int(sys.argv[1]) if len(sys.argv) > 1 else 6000
rnd = random.Random(int(sys.argv[2]) if len(sys.argv) > 2 else 1)

print("// generated by gen_fanout.py, N=%d" % n)
print("module fanout_top (input clk, input din, output dout);")
print("    reg [11:0] cnt = 12'd0;")
print("    always @(posedge clk) cnt <= cnt + 12'd1;")
print("    wire ce = (cnt[5:0] == 6'b101010) ^ din;")
print("    reg [%d:0] r = 0;" % (n - 1))
print("    always @(posedge clk) if (ce) begin")
for i in range(n):
    a, b, c = (rnd.randrange(n) for _ in range(3))
    print(f"        r[{i}] <= r[{a}] ^ r[{b}] ^ (r[{c}] & r[{(i - 1) % n}]);")
print("    end")
print("    reg d;")
print("    always @(posedge clk) d <= ^r;")
print("    assign dout = d;")
print("endmodule")
